# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: CI

on:
  pull_request:

# Automatically cancel any previous runs of this workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [snowflake-ci, bigquery-ci]
    env:
      # Snowflake
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER_CI: ${{ secrets.SNOWFLAKE_CI_USER }}
      SNOWFLAKE_PASSWORD_CI: ${{ secrets.SNOWFLAKE_CI_USER_PASSWORD }}
      SNOWFLAKE_DATABASE_CI: DBT_PACKAGE_CI
      SNOWFLAKE_ROLE_CI: PACKAGE_CI_ROLE
      SNOWFLAKE_WAREHOUSE_CI: PACKAGE_CI_WH
      # BigQuery
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        if: matrix.target == 'bigquery-ci'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with: { enable-cache: true }

      - name: Install dependencies
        run: uv sync --no-default-groups --group dbt

      - name: Run integration tests
        env:
          SNOWFLAKE_SCHEMA_CI: DBT_CI_${{ github.event.number }}
          BIGQUERY_DATASET: dbt_ci_${{ github.event.number }}
        run: |
          uv run ./run_test.sh ${{ matrix.target }}
